services:
  # Backend Web Service
  - type: web
    name: be-todo
    env: docker
    rootDir: todo-app
    dockerfilePath: ./todo-app/backend/Dockerfile
    dockerContext: ./todo-app/backend
    envVars:
      - key: DB_HOST
        value: dpg-d8251egg4nts73fh14t0-a.oregon-postgres.render.com
      - key: DB_USER
        value: todo_db_35da_user
      - key: DB_PASSWORD
        value: lNP2vgzglkCvFAIyFUd70aj7AzJ7u2vN
      - key: DB_NAME
        value: todo_db_35da
      - key: DB_PORT
        value: 5432
      - key: PORT
        value: 5000

  # Frontend Web Service
  - type: web
    name: fe-todo
    env: docker
    rootDir: todo-app
    dockerfilePath: ./todo-app/frontend/Dockerfile
    dockerContext: ./todo-app/frontend
    envVars:
      - key: REACT_APP_API_URL
        value: https://be-todo-02240360-vzia.onrender.com
